[project]
name = "comfydock-cli"
version = "1.0.0"
description = "ComfyDock CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "comfydock-core",
    "argcomplete>=3.5.0",
]

[project.scripts]
comfydock = "comfydock_cli.cli:main"
cfd = "comfydock_cli.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
comfydock-core = { workspace = true }